package scoutingapp;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Trogtor
 */


import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import java.awt.Font;
import javax.swing.JCheckBox;


public class PracticeFrame extends javax.swing.JFrame {

    int numTotes;
    int teamNumb;
    int matchNum;
    int autoPoints;
    int teleOpPoints;
    int foulPoints;
    int gamePoints;
    String name;
    int autoGears;
    int autoLowGoal;
    int autoHighGoal;
    int lowBar;
    int teleGears;
    int teleLowGoal;
    int teleHighGoal;
    boolean touchPad;
    boolean baseline;
    int high;
    int low;
    int total;

    String notes;
    String yn;
    boolean capturePoints;
    boolean breachPoints;
    boolean climbingPoints;
    int breached;
    int captured;
    int climbed;
    int extraPoints;
    int totalUpdate;
    
    
    

    /**
     * Creates new form PracticeFrame
     */
    public PracticeFrame() {
        initComponents();
        teamNumb = -1;
        autoPoints = 0;
        teleOpPoints = 0;
        foulPoints = 0;
        gamePoints = 0;
        name = "";
        baseline = false;
        autoGears = 0;
        autoLowGoal = 0;
        autoHighGoal = 0;
        lowBar = 0;
        teleGears = 0;
        teleLowGoal = 0;
        teleHighGoal = 0;
        touchPad = false;
        high = 0;
        low = 0;
        extraPoints = 0;
        climbed = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        textArea1 = new java.awt.TextArea();
        jDialog1 = new javax.swing.JDialog();
        InternalFrame = new javax.swing.JPanel();
        StandScout = new javax.swing.JLabel();
        autoScoring = new javax.swing.JLabel();
        teleGearsTxt = new javax.swing.JLabel();
        autoGearsTxt = new javax.swing.JLabel();
        autoLowGoalTxt = new javax.swing.JLabel();
        autoHighGoalTxt = new javax.swing.JLabel();
        autoGearsCount = new javax.swing.JSpinner();
        autoLowGoalCount = new javax.swing.JSpinner();
        teamNumTxt = new javax.swing.JTextField();
        theTeamNum = new javax.swing.JLabel();
        match = new javax.swing.JLabel();
        matchNumTxt = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel21 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        teleLowGoalTxt = new javax.swing.JLabel();
        teleHighGoalTxt = new javax.swing.JLabel();
        baselineTxt = new javax.swing.JLabel();
        touchPadTxt = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        teleGearsCount = new javax.swing.JSpinner();
        teleLowGoalCount = new javax.swing.JSpinner();
        teleHighGoalCount = new javax.swing.JSpinner();
        autoHighGoalCount = new javax.swing.JSpinner();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InternalFrame.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.red, java.awt.Color.black));
        InternalFrame.setForeground(new java.awt.Color(255, 255, 255));

        StandScout.setFont(new java.awt.Font("Tekton Pro", 1, 20)); // NOI18N
        StandScout.setText("Torbots Stand Scouting");
        StandScout.setToolTipText("");
        StandScout.setAlignmentX(0.5F);

        autoScoring.setFont(new java.awt.Font("Tekton Pro", 1, 14)); // NOI18N
        autoScoring.setText("Autonomous");
        autoScoring.setToolTipText("");

        teleGearsTxt.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        teleGearsTxt.setText("Gears Delivered");
        teleGearsTxt.setToolTipText("");

        autoGearsTxt.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        autoGearsTxt.setText("Gears Delivered");
        autoGearsTxt.setToolTipText("");

        autoLowGoalTxt.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        autoLowGoalTxt.setText("Low Goal");
        autoLowGoalTxt.setToolTipText("");

        autoHighGoalTxt.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        autoHighGoalTxt.setText("High Goal");
        autoHighGoalTxt.setToolTipText("");

        autoGearsCount.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        autoGearsCount.setModel(new javax.swing.SpinnerNumberModel(0, 0, 8, 1));
        autoGearsCount.setToolTipText("");
        autoGearsCount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                autoGearsCountFocusLost(evt);
            }
        });

        autoLowGoalCount.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        autoLowGoalCount.setModel(new javax.swing.SpinnerNumberModel(0, 0, 8, 1));
        autoLowGoalCount.setToolTipText("");
        autoLowGoalCount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                autoLowGoalCountFocusLost(evt);
            }
        });

        teamNumTxt.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        teamNumTxt.setToolTipText("");
        teamNumTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                teamNumTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                teamNumTxtFocusLost(evt);
            }
        });
        teamNumTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamNumTxtActionPerformed(evt);
            }
        });

        theTeamNum.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        theTeamNum.setText("Team #");
        theTeamNum.setToolTipText("");

        match.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        match.setText("Match #");
        match.setToolTipText("");

        matchNumTxt.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        matchNumTxt.setToolTipText("");
        matchNumTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                matchNumTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                matchNumTxtFocusLost(evt);
            }
        });

        saveButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jLabel21.setText("Notes:");

        jLabel30.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jLabel30.setText("Scoring Info:");

        teleLowGoalTxt.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        teleLowGoalTxt.setText("Low Goal");
        teleLowGoalTxt.setToolTipText("");

        teleHighGoalTxt.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        teleHighGoalTxt.setText("High Goal");
        teleHighGoalTxt.setToolTipText("");

        baselineTxt.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        baselineTxt.setText("Baseline");
        baselineTxt.setToolTipText("");

        touchPadTxt.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        touchPadTxt.setText("Touchpad");
        touchPadTxt.setToolTipText("");

        jLabel35.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N

        teleGearsCount.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        teleGearsCount.setModel(new javax.swing.SpinnerNumberModel(0, 0, 8, 1));
        teleGearsCount.setToolTipText("");
        teleGearsCount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                teleGearsCountFocusLost(evt);
            }
        });

        teleLowGoalCount.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        teleLowGoalCount.setModel(new javax.swing.SpinnerNumberModel(0, 0, 8, 1));
        teleLowGoalCount.setToolTipText("");
        teleLowGoalCount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                teleLowGoalCountFocusLost(evt);
            }
        });

        teleHighGoalCount.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        teleHighGoalCount.setModel(new javax.swing.SpinnerNumberModel(0, 0, 8, 1));
        teleHighGoalCount.setToolTipText("");
        teleHighGoalCount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                teleHighGoalCountFocusLost(evt);
            }
        });

        autoHighGoalCount.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        autoHighGoalCount.setModel(new javax.swing.SpinnerNumberModel(0, 0, 8, 1));
        autoHighGoalCount.setToolTipText("");
        autoHighGoalCount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                autoHighGoalCountFocusLost(evt);
            }
        });
        extra = new javax.swing.JTextArea();
        
                extra.setColumns(20);
                extra.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
                extra.setRows(5);
                extra.setToolTipText("");
        
        JLabel label = new JLabel();
        label.setToolTipText("");
        label.setText("Tele-Op");
        label.setFont(new Font("Dialog", Font.BOLD, 14));
        
        JCheckBox baseline = new JCheckBox("Reached?");
        baseline.setFont(new Font("Tahoma", Font.PLAIN, 14));
        
        JCheckBox chckbxActivated = new JCheckBox("Activated?");
        chckbxActivated.setFont(new Font("Tahoma", Font.PLAIN, 14));
        jTextArea1 = new javax.swing.JTextArea();
        
                jTextArea1.setEditable(false);
                jTextArea1.setColumns(20);
                jTextArea1.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
                jTextArea1.setRows(5);
                jTextArea1.setText("Autonomous Points:\n"
                        + "\n"
                        + "REACHING the BASELINE = 5 Points\n"
                        + "3 FUEL in Low Efficiency GOAL = 1 Point and 1 kPa\n"
                        + "1 FUEL in High Efficiency GOAL = 1 Point and 1 kPa\n"
                        + "Each ROTOR Turning = 60 Points\n"
                        + "\n"
                        + "Tele-Op Points:\n"
                        + "9 FUEL in Low Efficiency GOAL = 1 Point and 1 kPa\n"
                        + "3 FUEL in High Efficiency GOAL = 1 Point and 1 kPa\n"
                        + "Each ROTOR Turning = 40 Points\n"
                        + "TOUCHPAD activated by a ROBOT = 50 Points\n"
                        + "\n"
                        + "All 4 ROTORS Turning = 1 RANKING Point (100 Points in Playoff Rounds)" + "\n"
                        + "ALLIANCE meets or exceeds 40 kPa = 1 RANKING Point (20 Points in Playoff Rounds)");

        javax.swing.GroupLayout InternalFrameLayout = new javax.swing.GroupLayout(InternalFrame);
        InternalFrameLayout.setHorizontalGroup(
        	InternalFrameLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(InternalFrameLayout.createSequentialGroup()
        			.addGroup(InternalFrameLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(InternalFrameLayout.createSequentialGroup()
        					.addGap(192)
        					.addComponent(StandScout))
        				.addGroup(InternalFrameLayout.createSequentialGroup()
        					.addGap(28)
        					.addGroup(InternalFrameLayout.createParallelGroup(Alignment.LEADING)
        						.addGroup(InternalFrameLayout.createSequentialGroup()
        							.addGap(6)
        							.addGroup(InternalFrameLayout.createParallelGroup(Alignment.LEADING)
        								.addComponent(theTeamNum)
        								.addComponent(teamNumTxt, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE))
        							.addGap(118)
        							.addGroup(InternalFrameLayout.createParallelGroup(Alignment.LEADING)
        								.addComponent(matchNumTxt, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
        								.addComponent(match)))
        						.addGroup(InternalFrameLayout.createSequentialGroup()
        							.addGap(137)
        							.addGroup(InternalFrameLayout.createParallelGroup(Alignment.LEADING)
        								.addComponent(teleGearsTxt)
        								.addComponent(teleGearsCount, GroupLayout.PREFERRED_SIZE, 80, GroupLayout.PREFERRED_SIZE)
        								.addComponent(autoGearsTxt)
        								.addComponent(autoGearsCount, GroupLayout.PREFERRED_SIZE, 80, GroupLayout.PREFERRED_SIZE)))
        						.addGroup(InternalFrameLayout.createSequentialGroup()
        							.addGap(598)
        							.addComponent(jLabel35))
        						.addGroup(InternalFrameLayout.createSequentialGroup()
        							.addGap(4)
        							.addGroup(InternalFrameLayout.createParallelGroup(Alignment.LEADING)
        								.addComponent(autoScoring)
        								.addGroup(InternalFrameLayout.createSequentialGroup()
        									.addGroup(InternalFrameLayout.createParallelGroup(Alignment.LEADING)
        										.addComponent(baseline)
        										.addComponent(baselineTxt)
        										.addComponent(label, GroupLayout.PREFERRED_SIZE, 88, GroupLayout.PREFERRED_SIZE)
        										.addComponent(touchPadTxt)
        										.addComponent(chckbxActivated))
        									.addGap(186)
        									.addGroup(InternalFrameLayout.createParallelGroup(Alignment.LEADING)
        										.addComponent(autoLowGoalTxt)
        										.addComponent(autoLowGoalCount, GroupLayout.PREFERRED_SIZE, 80, GroupLayout.PREFERRED_SIZE)
        										.addComponent(teleLowGoalTxt)
        										.addComponent(teleLowGoalCount, GroupLayout.PREFERRED_SIZE, 80, GroupLayout.PREFERRED_SIZE))
        									.addGap(46)
        									.addGroup(InternalFrameLayout.createParallelGroup(Alignment.LEADING)
        										.addComponent(teleHighGoalCount, GroupLayout.PREFERRED_SIZE, 80, GroupLayout.PREFERRED_SIZE)
        										.addComponent(teleHighGoalTxt)
        										.addComponent(autoHighGoalTxt)
        										.addComponent(autoHighGoalCount, GroupLayout.PREFERRED_SIZE, 80, GroupLayout.PREFERRED_SIZE)))
        								.addGroup(InternalFrameLayout.createSequentialGroup()
        									.addComponent(jLabel21)
        									.addPreferredGap(ComponentPlacement.RELATED)
        									.addGroup(InternalFrameLayout.createParallelGroup(Alignment.LEADING)
        										.addComponent(saveButton, GroupLayout.PREFERRED_SIZE, 176, GroupLayout.PREFERRED_SIZE)
        										.addComponent(extra, GroupLayout.PREFERRED_SIZE, 567, GroupLayout.PREFERRED_SIZE))))))))
        			.addGroup(InternalFrameLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(InternalFrameLayout.createParallelGroup(Alignment.LEADING)
        					.addGroup(InternalFrameLayout.createSequentialGroup()
        						.addPreferredGap(ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
        						.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addGap(579))
        					.addGroup(InternalFrameLayout.createSequentialGroup()
        						.addGap(4)
        						.addComponent(jLabel30)
        						.addContainerGap()))
        				.addGroup(InternalFrameLayout.createSequentialGroup()
        					.addGap(64)
        					.addComponent(jTextArea1, GroupLayout.PREFERRED_SIZE, 565, GroupLayout.PREFERRED_SIZE)
        					.addContainerGap())))
        );
        InternalFrameLayout.setVerticalGroup(
        	InternalFrameLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(InternalFrameLayout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(InternalFrameLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(StandScout)
        				.addComponent(jLabel30))
        			.addGap(18)
        			.addGroup(InternalFrameLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(InternalFrameLayout.createSequentialGroup()
        					.addComponent(jLabel35)
        					.addGap(13)
        					.addGroup(InternalFrameLayout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(theTeamNum)
        						.addComponent(match))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(InternalFrameLayout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(teamNumTxt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(matchNumTxt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGap(32)
        					.addComponent(autoScoring)
        					.addGap(18)
        					.addGroup(InternalFrameLayout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(autoLowGoalTxt)
        						.addComponent(baselineTxt)
        						.addComponent(autoGearsTxt)
        						.addComponent(autoHighGoalTxt))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(InternalFrameLayout.createParallelGroup(Alignment.LEADING)
        						.addGroup(InternalFrameLayout.createParallelGroup(Alignment.BASELINE)
        							.addComponent(autoLowGoalCount, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        							.addComponent(autoHighGoalCount, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        						.addGroup(InternalFrameLayout.createParallelGroup(Alignment.BASELINE)
        							.addComponent(baseline)
        							.addComponent(autoGearsCount, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        					.addGap(19)
        					.addComponent(label, GroupLayout.PREFERRED_SIZE, 19, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addGroup(InternalFrameLayout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(teleLowGoalTxt)
        						.addComponent(touchPadTxt)
        						.addComponent(teleGearsTxt)
        						.addComponent(teleHighGoalTxt))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(InternalFrameLayout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(teleLowGoalCount, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(chckbxActivated)
        						.addComponent(teleGearsCount, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(teleHighGoalCount, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGap(44)
        					.addGroup(InternalFrameLayout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel21)
        						.addComponent(extra, GroupLayout.PREFERRED_SIZE, 193, GroupLayout.PREFERRED_SIZE)))
        				.addComponent(jTextArea1, GroupLayout.PREFERRED_SIZE, 375, GroupLayout.PREFERRED_SIZE))
        			.addGap(22)
        			.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(100)
        			.addComponent(saveButton, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
        			.addGap(192))
        );
        InternalFrame.setLayout(InternalFrameLayout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InternalFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InternalFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void autoHighGoalCountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_autoHighGoalCountFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_autoHighGoalCountFocusLost

    private void teleHighGoalCountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teleHighGoalCountFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_teleHighGoalCountFocusLost

    private void teleLowGoalCountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teleLowGoalCountFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_teleLowGoalCountFocusLost

    private void teleGearsCountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teleGearsCountFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_teleGearsCountFocusLost

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        points();
        setAllValues();
        makeCSV();
        clearForm();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void matchNumTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_matchNumTxtFocusLost
        // TODO add your handling code here:
        try {
            matchNum = Integer.parseInt(matchNumTxt.getText());
        } catch (NumberFormatException e) {
            matchNumTxt.setText("Enter Valid Number");
        }
    }//GEN-LAST:event_matchNumTxtFocusLost

    private void matchNumTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_matchNumTxtFocusGained
        // TODO add your handling code here:
        matchNumTxt.setText("");
    }//GEN-LAST:event_matchNumTxtFocusGained

    private void teamNumTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamNumTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teamNumTxtActionPerformed

    private void teamNumTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teamNumTxtFocusLost
        // TODO add your handling code here:

        try {
            teamNumb = Integer.parseInt(teamNumTxt.getText());
        } catch (NumberFormatException e) {
            teamNumTxt.setText("Enter Valid Number");
        }

        //        String filename = "Team Number " + teamNumb + " " + name + ".txt";
        //        BufferedReader br = null;
        //        String text = "";
        //        String str;
        //        try {
            //
            //            br = new BufferedReader(new FileReader(filename));
            //            while ((str = br.readLine()) != null) {
                //                text += str + "\n";
                //                jTextArea3.setText(text);
                //            }
            //        } catch (FileNotFoundException e) {
            //            System.out.println("Fail");
            //        } catch (IOException e) {
            //        } finally {
            //            if (br != null) {
                //                try {
                    //                    br.close();
                    //                } catch (IOException e) {
                    //                }
                //            }
            //        }
    }//GEN-LAST:event_teamNumTxtFocusLost

    private void teamNumTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teamNumTxtFocusGained
        // TODO add your handling code here:
        teamNumTxt.setText("");
    }//GEN-LAST:event_teamNumTxtFocusGained

    private void autoLowGoalCountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_autoLowGoalCountFocusLost
        // TODO add your handling code here:
        autoLowGoal = Integer.parseInt(autoLowGoalCount.getValue().toString());
    }//GEN-LAST:event_autoLowGoalCountFocusLost

    private void autoGearsCountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_autoGearsCountFocusLost
        // TODO add your handling code here:
        autoGears = Integer.parseInt(autoGearsCount.getValue().toString());
    }//GEN-LAST:event_autoGearsCountFocusLost

    /**
     * @param args the command line arguments
     */
    public void setAllValues() {
        baseline = baseline.isSelected(); //EDIT get check box to work probably have to use other variables
        if (baseline == true){
            baseline = true;
        }
        else{
            baseline = false;
        }
        capturePoints = capture.isSelected();
        if(capture.isSelected()){
            captured = 25;
        }
        else{
            captured = 0;
        }
        climbingPoints = capture1.isSelected();
        if (climbingPoints == true){
            yn = "Yes";
        }
        else{
            yn = "No";
        }

        
        numTotes = baseline + autoGears + autoLowGoal + lowBar + teleLowGoal + teleHighGoal + touchPad;
        gamePoints = teleOpPoints + autoPoints - foulPoints;
        
        extraPoints = breached + captured;
        notes = extra.getText();
    }

    public void points() {
        autoGears = (Integer.parseInt(autoGearsCount.getValue().toString())) * 5;
        autoLowGoal = (Integer.parseInt(autoLowGoalCount.getValue().toString())) * 5;
        autoHighGoal = (Integer.parseInt(autoHighGoalCount.getValue().toString())) * 5;
        teleGears = (Integer.parseInt(teleGearsCount.getValue().toString())) * 5;
        teleLowGoal = (Integer.parseInt(teleLowGoalCount.getValue().toString())) * 5;
        teleHighGoal = (Integer.parseInt(teleHighGoalCount.getValue().toString())) * 5;
        //EDIT point values
    }

    public void makeCSV() {
        String fileName = "Match " + matchNum + " " + teamNumb + ".csv";
        try {
            FileWriter writer = new FileWriter(fileName, true);
            writer.append("Match: " + matchNum + ", " + "Team #: " + teamNumb + ", " + "Autonomous Points: " + autoPoints + ", " + "Tele-Op Points: " + teleOpPoints
                    + "Foul Points: " + foulPoints + ", " + "Total Points: " + total + ", " + "Breach/Capture Points: " + extraPoints + ", " + "Climbing: " + yn + "\n"
                    + ", " + "Auto Gears: " + Integer.parseInt(autoGearsCount.getValue().toString()) + ", " + "autoLowGoal: "
                    + Integer.parseInt(autoLowGoalCount.getValue().toString()) + ", " + "Rock Wall: " + Integer.parseInt(autoHighGoalCount.getValue().toString()) + ", " + ","
                    + "See-Saw: " + Integer.parseInt(teleGearsCount.getValue().toString()) + ", " + "teleLowGoal: " + Integer.parseInt(teleLowGoalCount.getValue().toString()) + ", " + "teleHighGoal: "
                    + Integer.parseInt(teleHighGoalCount.getValue().toString()) + ", " + "Total Points By themselves: " + totalUpdate + "\n" + notes + "\n");
            writer.flush();
            writer.close();
        } catch (IOException e) {
        }
    }

    public void run() {
        validate();
    }

    public void clearForm() {
        teamNumTxt.setText("");
        matchNumTxt.setText("");
        jTextArea1.setText("Autonomous Points:\n"
                + "\n"
                + "REACHING the BASELINE = 5 Points\n"
                + "3 FUEL in Low Efficiency GOAL = 1 Point and 1 kPa\n"
                + "1 FUEL in High Efficiency GOAL = 1 Point and 1 kPa\n"
                + "Each ROTOR Turning = 60 Points\n"
                + "\n"
                + "Tele-Op Points:\n"
                + "9 FUEL in Low Efficiency GOAL = 1 Point and 1 kPa\n"
                + "3 FUEL in High Efficiency GOAL = 1 Point and 1 kPa\n"
                + "Each ROTOR Turning = 40 Points\n"
                + "TOUCHPAD activated by a ROBOT = 50 Points\n"
                + "\n"
                + "All 4 ROTORS Turning = 1 RANKING Point (100 Points in Playoff Rounds)" + "\n"
                + "ALLIANCE meets or exceeds 40 kPa = 1 RANKING Point (20 Points in Playoff Rounds)");
        extra.setText(" ");
        //jTextArea3.setText(" ");
        saveButton.setText("Save");
        autoGearsCount.setValue(new Integer(0));
        autoLowGoalCount.setValue(new Integer(0));
        autoHighGoalCount.setValue(new Integer(0));
        teleGearsCount.setValue(new Integer(0));
        teleLowGoalCount.setValue(new Integer(0));
        teleHighGoalCount.setValue(new Integer(0));
        touchPad = false;
        baseline = false;
        totalUpdate = 0;
    }
    
    public void MainClass() {
    this.setTitle("Picture Application");
    this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    JPanel panel1 = new JPanel();
    ImageIcon pic = new ImageIcon("Portcullis.png");
    panel1.add(new JLabel(pic));
    getContentPane().add(panel1);
    this.pack();
    this.setVisible(true);
  }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PracticeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PracticeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PracticeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PracticeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PracticeFrame().setVisible(true);
            }
        });
        
        
    }
    private javax.swing.JPanel InternalFrame;
    private javax.swing.JLabel StandScout;
    private javax.swing.JLabel autoScoring;
    private javax.swing.JSpinner teleHighGoalCount;
    private javax.swing.JLabel teleHighGoalTxt;
    private javax.swing.JSpinner autoLowGoalCount;
    private javax.swing.JLabel autoLowGoalTxt;
    private javax.swing.JTextArea extra;
    private javax.swing.JLabel baselineTxt;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel match;
    private javax.swing.JTextField matchNumTxt;
    private javax.swing.JSpinner autoGearsCount;
    private javax.swing.JLabel autoGearsTxt;
    private javax.swing.JSpinner teleLowGoalCount;
    private javax.swing.JLabel teleLowGoalTxt;
    private javax.swing.JSpinner autoHighGoalCount;
    private javax.swing.JLabel autoHighGoalTxt;
    private javax.swing.JLabel touchPadTxt;
    private javax.swing.JButton saveButton;
    private javax.swing.JSpinner teleGearsCount;
    private javax.swing.JLabel teleGearsTxt;
    private javax.swing.JTextField teamNumTxt;
    private java.awt.TextArea textArea1;
    private javax.swing.JLabel theTeamNum;
}
